/*
 * Copyright (c) 2024, Univerisity of Washington
 * Copyright (c) 2019, Bandhav Veluri
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef DRAMFS_INTF_H
#define DRAMFS_INTF_H

#include "lfs.h"

// Toplevel filesystem struct
extern lfs_t __attribute__((weak)) lfs;

// File system configuration structure
// Initalized externally and can be generated by mkdramfs
extern const struct lfs_config __attribute__((weak)) lfs_config;

// Exit routine: exit() calls this routine
// Definition provided externally by user
extern void __attribute__((weak)) dramfs_exit(int fd);

// Utility to print a char to console
// Definition provided externally by user
extern void __attribute__((weak)) dramfs_putchar(int ch);

// Utility to get a char from console
// Definition provided externally by user
extern int __attribute__((weak)) dramfs_getchar(void);

#endif
